name: Stonks
version: 1.0
api-version: 1.14
main: dev.tycho.stonks.Stonks
authors:
  - TychoVI
  - Tsarcasm
  - JRoy
depend: [PluginLibrary, Vault, ChestShop, Essentials]
commands:
  company:
    description: Main command that houses rest.
    usage: /company
    aliases: [stonks, comp]