name: Stonks
version: 1.0
main: nl.tychovi.stonks.Stonks
authors:
  - TychoVI
  - Tsarcasm
  - JRoy
depend:
  - Vault
commands:
  company:
    description: Main command that houses rest.
    usage: /company
    aliases: [stonks, comp]